import { AgentNodeConfig } from "../types";

export const AGENT_NODES: AgentNodeConfig[] = [
  {
    id: "preprocessing",
    role: "Preprocessing Stage",
    label: "Data Preprocessing",
    description: "Splits raw documents into semantic chunks and builds high-dimensional vector embeddings.",
    pipelineOrder: 1,
    workflowStates: ["CHUNKING", "CHUNKED", "EMBEDDING"],
    artifactIn: null,
    artifactOut: ["VectorIndexReference"],
    isStage: true,
  },
  {
    id: "source_understanding",
    role: "Source Understanding Analyst",
    label: "Source Understanding",
    description: "Performs category coverage analysis and highlights document warnings.",
    pipelineOrder: 2,
    workflowStates: ["SOURCE_ANALYZING", "SOURCE_ANALYZED"],
    artifactIn: ["VectorIndexReference"],
    artifactOut: ["source_understanding_report"],
  },
  {
    id: "intake_planner",
    role: "Intake Planner",
    label: "Intake Planner",
    description: "Drafts and structures the benchmark evaluation plan with difficulty splits.",
    pipelineOrder: 3,
    workflowStates: ["PLANNING", "PLAN_READY", "WAITING_FOR_PLAN_APPROVAL", "PLAN_APPROVED"],
    artifactIn: ["source_understanding_report"],
    artifactOut: ["approved_benchmark_plan"],
  },
  {
    id: "generator",
    role: "Benchmark Generator",
    label: "Sample Generator",
    description: "Synthesizes QA test evaluation pairs using chunk contexts.",
    pipelineOrder: 4,
    workflowStates: ["GENERATING", "VALIDATING"],
    artifactIn: ["approved_benchmark_plan"],
    artifactOut: ["generated_samples"],
  },
  {
    id: "evaluator",
    role: "Quality Evaluator",
    label: "Quality Evaluator",
    description: "Runs faithfulness, relevance, and risk checks on generated samples.",
    pipelineOrder: 5,
    workflowStates: ["EVALUATING", "REPAIRING", "WAITING_FOR_SAMPLE_REVIEW"],
    artifactIn: ["generated_samples"],
    artifactOut: ["evaluation_report"],
  },
  {
    id: "exporter",
    role: "Export Packager",
    label: "Package Exporter",
    description: "Compiles finalized and approved evaluation samples into zip archive.",
    pipelineOrder: 6,
    workflowStates: ["EXPORTING", "EXPORT_READY", "DONE"],
    artifactIn: ["evaluation_report"],
    artifactOut: ["export_package"],
  },
];
