import React, { useState } from "react";
import { useMissionControlStore } from "../../../store/useMissionControlStore";
import { useEvaluatorSamples } from "./useEvaluatorSamples";
import SummaryMetrics from "./components/SummaryMetrics";
import EvaluationCard from "./components/EvaluationCard";
import Section from "../../components/Section";
import Pagination from "../../components/Pagination";

interface EvaluatorViewerProps {
  projectId: string;
}

export default function EvaluatorViewer({ projectId }: EvaluatorViewerProps) {
  const { demoMode } = useMissionControlStore();
  const { samples, loading } = useEvaluatorSamples(projectId, demoMode);
  
  // Search, filter, and pagination states
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedDecision, setSelectedDecision] = useState<string>("all");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-16 gap-3 select-none">
        <div className="relative w-8 h-8">
          <div className="absolute inset-0 rounded-full border-2 border-indigo-500/20"></div>
          <div className="absolute inset-0 rounded-full border-2 border-t-indigo-500 animate-spin"></div>
        </div>
        <p className="text-[11px] font-mono text-slate-500 uppercase tracking-widest">
          Analyzing Evaluation Logs...
        </p>
      </div>
    );
  }

  // Reset page count on filter or search changes
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value);
    setCurrentPage(1);
  };

  const handleDecisionFilterChange = (dec: string) => {
    setSelectedDecision(dec);
    setCurrentPage(1);
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
    const scrollContainer = document.querySelector(".custom-workspace-scroll");
    if (scrollContainer) {
      scrollContainer.scrollTo({ top: 0, behavior: "smooth" });
    }
  };

  // Filter samples based on search query and decision
  const filteredSamples = samples.filter((sample) => {
    const matchesSearch =
      (sample.question || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
      (sample.expected_answer || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
      (sample.category || "").toLowerCase().includes(searchQuery.toLowerCase());
      
    let matchesDecision = false;
    if (selectedDecision === "all") {
      matchesDecision = true;
    } else if (selectedDecision === "pass") {
      matchesDecision = sample.decision === "pass" && sample.retry_count === 0;
    } else if (selectedDecision === "repair") {
      matchesDecision = sample.decision === "repair" || sample.retry_count > 0;
    } else {
      matchesDecision = (sample.decision || "").toLowerCase() === selectedDecision.toLowerCase();
    }
      
    return matchesSearch && matchesDecision;
  });

  // Calculate pagination details
  const totalPages = Math.ceil(filteredSamples.length / itemsPerPage);
  const paginatedSamples = filteredSamples.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  return (
    <div className="flex flex-col gap-5 select-none text-left">
      
      {/* High-level Summary Metrics dashboard */}
      <SummaryMetrics samples={samples} />

      {/* Main workspace section */}
      <Section title="Quality Evaluation Workspace" className="select-text">
        <div className="space-y-4">
          <p className="text-slate-400 text-xs">
            Review the benchmark evaluation logs and repair negotiation traces generated by the Quality Evaluator Agent. Inspect check failures, novelty scores, and human review routing statuses.
          </p>

          {/* Search and filter row */}
          <div className="flex flex-col sm:flex-row gap-3 border-b border-white/[0.04] pb-4 select-none">
            <input
              type="text"
              placeholder="Search evaluated questions, answers, or categories..."
              value={searchQuery}
              onChange={handleSearchChange}
              className="flex-1 bg-white/[0.02] border border-white/10 rounded-xl px-3 py-1.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500/50 transition-all font-sans"
            />
            
            <div className="flex items-center gap-1.5">
              <span className="text-[10px] font-mono text-slate-500 uppercase font-semibold mr-1">Decision:</span>
              {["all", "pass", "repair", "human_review", "reject"].map((dec) => {
                const label = dec === "human_review" ? "review" : dec;
                return (
                  <button
                    key={dec}
                    onClick={() => handleDecisionFilterChange(dec)}
                    className={`px-2.5 py-1 rounded-lg border text-[10px] font-mono font-medium capitalize transition-all cursor-pointer ${
                      selectedDecision === dec
                        ? "bg-indigo-500/10 text-indigo-400 border-indigo-500/30"
                        : "bg-white/[0.01] text-slate-450 border-white/5 hover:bg-white/[0.02] hover:border-white/10"
                    }`}
                  >
                    {label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Cards Stack */}
          <div className="space-y-4">
            {paginatedSamples.length > 0 ? (
              paginatedSamples.map((sample) => (
                <EvaluationCard key={sample.id} sample={sample} />
              ))
            ) : (
              <div className="text-center py-10 border border-dashed border-white/5 rounded-2xl bg-white/[0.01]">
                <p className="text-xs text-slate-500 italic">
                  No evaluated samples match the selected decision filter or search query.
                </p>
              </div>
            )}
          </div>

          {/* Pagination bar */}
          <Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            onPageChange={handlePageChange}
            totalItems={filteredSamples.length}
            itemsPerPage={itemsPerPage}
          />
        </div>
      </Section>

    </div>
  );
}
