import enum

class WorkflowState(str, enum.Enum):
    CREATED = "CREATED"
    FILES_UPLOADED = "FILES_UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    CHUNKING = "CHUNKING"
    CHUNKED = "CHUNKED"
    EMBEDDING = "EMBEDDING"
    SOURCE_ANALYZING = "SOURCE_ANALYZING"
    SOURCE_ANALYZED = "SOURCE_ANALYZED"
    PLANNING = "PLANNING"
    PLAN_READY = "PLAN_READY"
    WAITING_FOR_PLAN_APPROVAL = "WAITING_FOR_PLAN_APPROVAL"
    PLAN_APPROVED = "PLAN_APPROVED"
    GENERATING = "GENERATING"
    VALIDATING = "VALIDATING"
    EVALUATING = "EVALUATING"
    REPAIRING = "REPAIRING"
    WAITING_FOR_SAMPLE_REVIEW = "WAITING_FOR_SAMPLE_REVIEW"
    EXPORTING = "EXPORTING"
    EXPORT_READY = "EXPORT_READY"
    DONE = "DONE"
    FAILED = "FAILED"

class SampleStatus(str, enum.Enum):
    GENERATED = "GENERATED"
    EVALUATING = "EVALUATING"
    REPAIRING = "REPAIRING"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class DecisionType(str, enum.Enum):
    APPROVE = "approve"
    REJECT = "reject"
    EDIT = "edit"
    REGENERATE = "regenerate"
